name: Commit Checks
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read # Checkout the code

jobs:
  checks:
    name: Code Checks
    runs-on: nscloud-ubuntu-22.04-amd64-2x8
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Check Go formatting
        run: go fmt ./... && git diff --exit-code

      - name: Check Go mod is tidy
        run: go mod tidy && git diff --exit-code

      - name: Check that Go builds
        run: |
          go build -o . ./cmd/...

      - name: DO NOT MERGE
        uses: ./
        with:
          duration: 30m
          authorized-users: edganiukov,hugosantos,n-g,htr,nichtverstehen,gmichelo,attilaolah

      - name: Breakpoint on failure
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          duration: 30m
          authorized-users: edganiukov,hugosantos,n-g,htr,nichtverstehen,gmichelo,attilaolah
          slack-announce-channel: "#ci"
